// Package protocol defines the wire format for SQL statements and results.
//
// It's kept in a separate package since this code is entirely generated by the
// protobuf compile, and should not affect code coverage measurements.
package protocol
